package com.teslamotors.protocol.ble

enum class GattErrorType {

    ERR_CONNECTION_STATUS_CHANGE,
    ERR_SERVICES_DISCOVERY,
    ERR_CHARACTERISTIC_READ,
    ERR_CHARACTERISTIC_CHANGE,

    ERR_INNER_CHARACTERISTIC_WRITE,
    ERR_INNER_CHARACTERISTIC_LEGACY_WRITE,
    ERR_INNER_DESCRIPTOR_WRITE,
    ERR_INNER_DESCRIPTOR_LEGACY_WRITE,
    ERR_INNER_NOTIFICATIONS_ENABLE,
    ERR_INNER_NOTIFICATIONS_DISABLE
}