package com.teslamotors.protocol.util

import java.util.*

const val TESLA_BLUETOOTH_BEACON_UUID = "74278bda-b644-4520-8f0c-720eaf059935"
const val TESLA_BLUETOOTH_BEACON_LOCAL_NAME = "Saadbad01e89502c1C" // only for my car

private const val TESLA_SERVICE = "00000211-b2d1-43f0-9b88-960cebf8b91e"
private const val TESLA_TX_CHARACTERISTIC = "00000212-b2d1-43f0-9b88-960cebf8b91e"
private const val TESLA_RX_CHARACTERISTIC = "00000213-b2d1-43f0-9b88-960cebf8b91e"
private const val TESLA_RX_CHARACTERISTIC_DESCRIPTOR = "00002902-0000-1000-8000-00805f9b34fb"

val TESLA_SERVICE_UUID: UUID = UUID.fromString(TESLA_SERVICE)
val TESLA_TX_CHARACTERISTIC_UUID: UUID = UUID.fromString(TESLA_TX_CHARACTERISTIC)
val TESLA_RX_CHARACTERISTIC_UUID: UUID = UUID.fromString(TESLA_RX_CHARACTERISTIC)
val TESLA_RX_CHARACTERISTIC_DESCRIPTOR_UUID: UUID =
    UUID.fromString(TESLA_RX_CHARACTERISTIC_DESCRIPTOR)

//
const val STATUS_CODE_OK = 0
const val STATUS_CODE_ERR = -1

// ...
const val ACTION_CLIENT_MESSENGER = 200
const val ACTION_TOAST = 201

// scan and connect ...
const val ACTION_CONNECTING = 400
const val ACTION_CONNECTING_RESP = 401

const val ACTION_KEY_TO_WHITELIST_ADDING = 500
const val ACTION_KEY_TO_WHITELIST_ADDING_RESP = 501

const val ACTION_EPHEMERAL_KEY_REQUESTING = 600
const val ACTION_EPHEMERAL_KEY_REQUESTING_RESP = 601

const val ACTION_AUTHENTICATING = 700
const val ACTION_AUTHENTICATING_RESP = 701

const val ACTION_CLOSURES_REQUESTING = 800
const val ACTION_CLOSURES_REQUESTING_RESP = 801

const val ACTION_OVERLAY_CONTROLLER_SHOW = 1000

// ...

const val ACTION_OPEN_FRONT_PASSENGER_DOOR = "ACTION_OPEN_FRONT_PASSENGER_DOOR"
const val ACTION_OPEN_REAR_PASSENGER_DOOR = "ACTION_OPEN_REAR_PASSENGER_DOOR"